import type {
  CharacterDef,
  CharacterId,
  EnemyKind,
  GunStats,
  GunTier,
  LevelDef,
  UpgradeDef,
  WorldAnchor,
} from "./types";

export const RAINBOW = [0xff5a7a, 0xffa04a, 0xffe14a, 0x5ee07a, 0x4ab8ff, 0xb06bff, 0xff9aff];

export const CHARACTERS: CharacterDef[] = [
  { id: "rancher", name: "Rancher", emoji: "🤠", body: 0xffe8f4, pants: 0x4a3a6e, hat: 0xff5aa8 },
  { id: "cowgirl", name: "Cowgirl", emoji: "⭐", body: 0xffd0e8, pants: 0x5a3a28, hat: 0xffc84a },
  { id: "robot", name: "Bot-Bee", emoji: "🤖", body: 0x8ec8ff, pants: 0x3a5080, hat: 0xffe14a },
  { id: "wizard", name: "Mage", emoji: "🔮", body: 0xc9a0ff, pants: 0x3a2060, hat: 0xb06bff },
  { id: "dino_rider", name: "Dino", emoji: "🦖", body: 0x7ad46a, pants: 0x2a5030, hat: 0xff8a40 },
];

export function characterDef(id: CharacterId): CharacterDef {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}

export const GUN_TIERS: Record<GunTier, GunStats> = {
  0: {
    name: "Sparkle Sprinkler",
    damage: 34,
    fireRate: 4.2,
    bulletSpeed: 38,
    spread: 0.02,
    projectiles: 1,
    color: 0xff5a7a,
  },
  1: {
    name: "Prism Pumper",
    damage: 20,
    fireRate: 4.4,
    bulletSpeed: 38,
    spread: 0.12,
    projectiles: 3,
    color: 0xffe14a,
  },
  2: {
    name: "Rainbow Hose",
    damage: 40,
    fireRate: 5.0,
    bulletSpeed: 42,
    spread: 0.03,
    projectiles: 1,
    color: 0x4ab8ff,
  },
  3: {
    name: "Double Rainbow",
    damage: 30,
    fireRate: 5.4,
    bulletSpeed: 40,
    spread: 0.08,
    projectiles: 2,
    color: 0xb06bff,
  },
  4: {
    name: "Unicorn Laser",
    damage: 60,
    fireRate: 6.8,
    bulletSpeed: 56,
    spread: 0.01,
    projectiles: 1,
    color: 0xff9aff,
  },
};

export const UPGRADES: UpgradeDef[] = [
  {
    id: "hire_farmer",
    category: "crew",
    name: "Farmer",
    shortName: "Farmer",
    description: "Scoops for you.",
    baseCost: 30,
    costScale: 1.55,
    maxLevel: 3,
    worldShop: true,
    worldAnchor: "field",
  },
  {
    id: "hire_bot",
    category: "crew",
    name: "Robot",
    shortName: "Robot",
    description: "Auto-scoops.",
    baseCost: 90,
    costScale: 1.8,
    maxLevel: 3,
    worldShop: true,
    worldAnchor: "field",
  },
  {
    id: "harvest_speed",
    category: "chain",
    name: "Big Scoop",
    shortName: "Scoop+",
    description: "Faster scooping.",
    baseCost: 18,
    costScale: 1.28,
    maxLevel: 8,
    worldShop: true,
    worldAnchor: "field",
  },
  {
    id: "crop_yield",
    category: "chain",
    name: "Bigger Drops",
    shortName: "Yield+",
    description: "More per scoop.",
    baseCost: 22,
    costScale: 1.32,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "field",
  },
  {
    id: "hire_grinder",
    category: "crew",
    name: "Spa Crew",
    shortName: "Spa crew",
    description: "Washes & grinds.",
    baseCost: 55,
    costScale: 1.65,
    maxLevel: 2,
    worldShop: true,
    worldAnchor: "spa",
  },
  {
    id: "spa_speed",
    category: "chain",
    name: "Bubble Boost",
    shortName: "Spa+",
    description: "Spa faster.",
    baseCost: 24,
    costScale: 1.3,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "spa",
  },
  {
    id: "process_speed",
    category: "chain",
    name: "Glitter Grinder",
    shortName: "Grind+",
    description: "Grind faster.",
    baseCost: 26,
    costScale: 1.3,
    maxLevel: 8,
    worldShop: true,
    worldAnchor: "grind",
  },
  {
    id: "process_auto",
    category: "chain",
    name: "Auto Hopper",
    shortName: "Auto",
    description: "Auto-feed stations.",
    baseCost: 70,
    costScale: 1.85,
    maxLevel: 3,
    worldShop: true,
    worldAnchor: "grind",
  },
  {
    id: "pack_speed",
    category: "chain",
    name: "Bow Machine",
    shortName: "Box+",
    description: "Box faster.",
    baseCost: 28,
    costScale: 1.3,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "pack",
  },
  {
    id: "hire_vendor",
    category: "crew",
    name: "Seller",
    shortName: "Seller",
    description: "Boxes & sells.",
    baseCost: 65,
    costScale: 1.7,
    maxLevel: 2,
    worldShop: true,
    worldAnchor: "market",
  },
  {
    id: "sell_price",
    category: "chain",
    name: "Price Up",
    shortName: "Price+",
    description: "More coins per crate.",
    baseCost: 30,
    costScale: 1.35,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "market",
  },
  {
    id: "sell_speed",
    category: "chain",
    name: "Fast Sell",
    shortName: "Sell+",
    description: "Sell faster.",
    baseCost: 24,
    costScale: 1.28,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "market",
  },
  {
    id: "gun_tier",
    category: "gun",
    name: "Rainbow Gun",
    shortName: "Gun+",
    description: "Better gun.",
    baseCost: 60,
    costScale: 1.6,
    maxLevel: 4,
    worldShop: true,
    worldAnchor: "player",
  },
  {
    id: "gun_damage",
    category: "gun",
    name: "More Sparkle",
    shortName: "Dmg+",
    description: "+15% damage.",
    baseCost: 40,
    costScale: 1.4,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "player",
  },
  {
    id: "gun_rate",
    category: "gun",
    name: "Faster Hose",
    shortName: "Rate+",
    description: "+12% fire rate.",
    baseCost: 42,
    costScale: 1.4,
    maxLevel: 6,
    worldShop: true,
    worldAnchor: "player",
  },
  {
    id: "max_health",
    category: "player",
    name: "Sparkle Vest",
    shortName: "HP+",
    description: "+25 HP.",
    baseCost: 25,
    costScale: 1.35,
    maxLevel: 5,
    worldShop: true,
    worldAnchor: "player",
  },
  {
    id: "move_speed",
    category: "player",
    name: "Sneakers",
    shortName: "Speed+",
    description: "Move faster.",
    baseCost: 30,
    costScale: 1.4,
    maxLevel: 4,
    worldShop: true,
    worldAnchor: "player",
  },
];

export function upgradeCost(def: UpgradeDef, level: number) {
  return Math.floor(def.baseCost * Math.pow(def.costScale, level));
}

export function enemyStats(kind: EnemyKind, levelId: number) {
  const scale = 1 + (levelId - 1) * 0.05;
  switch (kind) {
    case "pest":
      return { hp: 16 * scale, speed: 2.4, damage: 2, radius: 0.6, color: 0xfff0f8, coin: 5, height: 1.0 };
    case "beetle":
      return { hp: 28 * scale, speed: 2.1, damage: 3, radius: 0.75, color: 0xe8d4ff, coin: 9, height: 1.15 };
    case "thief":
      return { hp: 22 * scale, speed: 3.2, damage: 2, radius: 0.6, color: 0xffd4a8, coin: 14, height: 1.2 };
    case "brute":
      return { hp: 70 * scale, speed: 1.7, damage: 5, radius: 1.1, color: 0xffb0d0, coin: 30, height: 1.9 };
    case "dino":
      return { hp: 40 * scale, speed: 2.0, damage: 4, radius: 0.95, color: 0x5ec86a, coin: 16, height: 1.5 };
    case "raptor":
      return { hp: 24 * scale, speed: 3.8, damage: 3, radius: 0.65, color: 0xff8a40, coin: 12, height: 1.1 };
  }
}

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: "Starter Paddock",
    subtitle: "Easy warm-up",
    width: 40,
    depth: 36,
    seed: 101,
    cropCount: 16,
    quota: 3,
    timeLimit: 380,
    spawn: { x: 0, z: 12 },
    spa: { x: -8, z: 4 },
    processor: { x: -8, z: -4 },
    packer: { x: 8, z: -4 },
    market: { x: 8, z: 4 },
    goalHint: "Scoop pink piles · wash · glitter · box · sell",
    enemyWaves: [{ delay: 120, kind: "pest", count: 1 }],
    platforms: [{ x: 0, y: 1.0, z: -12, w: 4, d: 3 }],
  },
  {
    id: 2,
    name: "Busy Meadow",
    subtitle: "Unicorns + dinos",
    width: 44,
    depth: 38,
    seed: 202,
    cropCount: 18,
    quota: 6,
    timeLimit: 360,
    spawn: { x: 0, z: 14 },
    spa: { x: -10, z: 5 },
    processor: { x: -10, z: -5 },
    packer: { x: 10, z: -5 },
    market: { x: 10, z: 5 },
    goalHint: "Tap the floating hire buttons near the pink shop",
    enemyWaves: [
      { delay: 70, kind: "pest", count: 1 },
      { delay: 100, kind: "raptor", count: 1 },
    ],
    platforms: [
      { x: -14, y: 1.2, z: 8, w: 4, d: 3 },
      { x: 14, y: 1.2, z: 8, w: 4, d: 3 },
    ],
  },
  {
    id: 3,
    name: "Glitter Canal",
    subtitle: "Dino visitors",
    width: 50,
    depth: 42,
    seed: 303,
    cropCount: 20,
    quota: 10,
    timeLimit: 330,
    spawn: { x: 0, z: 16 },
    spa: { x: -14, z: 6 },
    processor: { x: -14, z: -6 },
    packer: { x: 14, z: -6 },
    market: { x: 14, z: 6 },
    goalHint: "Hire a farmer when you can",
    enemyWaves: [
      { delay: 55, kind: "pest", count: 2 },
      { delay: 90, kind: "dino", count: 1 },
      { delay: 140, kind: "raptor", count: 1 },
    ],
    platforms: [
      { x: 0, y: 1.6, z: 0, w: 5, d: 4 },
      { x: -16, y: 1.2, z: 10, w: 4, d: 3 },
      { x: 16, y: 1.2, z: 10, w: 4, d: 3 },
    ],
  },
  {
    id: 4,
    name: "Moonlit Meadow",
    subtitle: "Mixed herd",
    width: 54,
    depth: 46,
    seed: 404,
    cropCount: 22,
    quota: 14,
    timeLimit: 340,
    spawn: { x: 0, z: 18 },
    spa: { x: -16, z: 6 },
    processor: { x: -16, z: -6 },
    packer: { x: 16, z: -6 },
    market: { x: 16, z: 6 },
    goalHint: "Automate the chain",
    enemyWaves: [
      { delay: 50, kind: "pest", count: 2 },
      { delay: 80, kind: "dino", count: 1 },
      { delay: 110, kind: "beetle", count: 1 },
      { delay: 150, kind: "raptor", count: 2 },
    ],
    platforms: [
      { x: -12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 0, y: 2.4, z: -10, w: 6, d: 4 },
    ],
  },
  {
    id: 5,
    name: "Sky Barn",
    subtitle: "Busy ranch",
    width: 56,
    depth: 48,
    seed: 505,
    cropCount: 24,
    quota: 18,
    timeLimit: 350,
    spawn: { x: 0, z: 18 },
    spa: { x: -15, z: 5 },
    processor: { x: -15, z: -7 },
    packer: { x: 15, z: -7 },
    market: { x: 15, z: 5 },
    goalHint: "Keep selling",
    enemyWaves: [
      { delay: 45, kind: "pest", count: 2 },
      { delay: 75, kind: "dino", count: 2 },
      { delay: 110, kind: "thief", count: 1 },
      { delay: 150, kind: "raptor", count: 2 },
    ],
    platforms: [
      { x: -18, y: 2.0, z: 4, w: 5, d: 4 },
      { x: 18, y: 2.0, z: 4, w: 5, d: 4 },
      { x: 0, y: 3.0, z: -8, w: 6, d: 5 },
    ],
  },
  {
    id: 6,
    name: "Final Ranch",
    subtitle: "Peak glitter",
    width: 60,
    depth: 50,
    seed: 606,
    cropCount: 28,
    quota: 22,
    timeLimit: 360,
    spawn: { x: 0, z: 20 },
    spa: { x: -18, z: 6 },
    processor: { x: -18, z: -8 },
    packer: { x: 18, z: -8 },
    market: { x: 18, z: 6 },
    goalHint: "Full automation",
    enemyWaves: [
      { delay: 40, kind: "pest", count: 3 },
      { delay: 70, kind: "dino", count: 2 },
      { delay: 100, kind: "raptor", count: 2 },
      { delay: 140, kind: "brute", count: 1 },
      { delay: 180, kind: "thief", count: 1 },
    ],
    platforms: [
      { x: -20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 0, y: 3.2, z: 0, w: 7, d: 5 },
    ],
  },
];
