import type { EnemyKind, GunStats, GunTier, LevelDef, UpgradeDef } from "./types";

export const RAINBOW = [0xff5a7a, 0xffa04a, 0xffe14a, 0x5ee07a, 0x4ab8ff, 0xb06bff, 0xff9aff];

export const GUN_TIERS: Record<GunTier, GunStats> = {
  0: {
    name: "Sparkle Sprinkler",
    damage: 28,
    fireRate: 3.6,
    bulletSpeed: 36,
    spread: 0.02,
    projectiles: 1,
    color: 0xff5a7a,
  },
  1: {
    name: "Prism Pumper",
    damage: 18,
    fireRate: 4.0,
    bulletSpeed: 36,
    spread: 0.12,
    projectiles: 3,
    color: 0xffe14a,
  },
  2: {
    name: "Rainbow Hose",
    damage: 36,
    fireRate: 4.8,
    bulletSpeed: 40,
    spread: 0.03,
    projectiles: 1,
    color: 0x4ab8ff,
  },
  3: {
    name: "Double Rainbow",
    damage: 28,
    fireRate: 5.2,
    bulletSpeed: 38,
    spread: 0.08,
    projectiles: 2,
    color: 0xb06bff,
  },
  4: {
    name: "Unicorn Laser",
    damage: 55,
    fireRate: 6.5,
    bulletSpeed: 54,
    spread: 0.01,
    projectiles: 1,
    color: 0xff9aff,
  },
};

export const UPGRADES: UpgradeDef[] = [
  {
    id: "gun_tier",
    category: "gun",
    name: "Rainbow Gun",
    description: "Optional combat upgrade.",
    baseCost: 80,
    costScale: 1.7,
    maxLevel: 4,
  },
  {
    id: "gun_damage",
    category: "gun",
    name: "More Sparkle",
    description: "+15% rainbow damage.",
    baseCost: 45,
    costScale: 1.45,
    maxLevel: 6,
  },
  {
    id: "gun_rate",
    category: "gun",
    name: "Faster Hose",
    description: "+12% fire rate.",
    baseCost: 50,
    costScale: 1.45,
    maxLevel: 6,
  },
  {
    id: "harvest_speed",
    category: "chain",
    name: "Poop Scoop",
    description: "Scoop piles faster; sweep a second nearby pile.",
    baseCost: 20,
    costScale: 1.3,
    maxLevel: 8,
  },
  {
    id: "crop_yield",
    category: "chain",
    name: "Bigger Drops",
    description: "More sparkle-poop per scoop.",
    baseCost: 25,
    costScale: 1.35,
    maxLevel: 6,
  },
  {
    id: "spa_speed",
    category: "chain",
    name: "Bubble Boost",
    description: "Poop Spa washes faster.",
    baseCost: 28,
    costScale: 1.35,
    maxLevel: 6,
  },
  {
    id: "process_speed",
    category: "chain",
    name: "Glitter Grinder",
    description: "Grinder runs faster.",
    baseCost: 30,
    costScale: 1.35,
    maxLevel: 8,
  },
  {
    id: "pack_speed",
    category: "chain",
    name: "Bow Machine",
    description: "Fancy Boxer packs glitter quicker.",
    baseCost: 32,
    costScale: 1.35,
    maxLevel: 6,
  },
  {
    id: "process_auto",
    category: "chain",
    name: "Auto Hopper",
    description: "Auto-feeds stations when you stand near them.",
    baseCost: 75,
    costScale: 1.9,
    maxLevel: 3,
  },
  {
    id: "sell_price",
    category: "chain",
    name: "Manure Hype",
    description: "Higher coins per boxed glitter crate.",
    baseCost: 35,
    costScale: 1.4,
    maxLevel: 6,
  },
  {
    id: "sell_speed",
    category: "chain",
    name: "Fast Haggle",
    description: "Sell crates faster.",
    baseCost: 28,
    costScale: 1.3,
    maxLevel: 6,
  },
  {
    id: "hire_farmer",
    category: "crew",
    name: "Hire Farmer",
    description: "Scoops sparkle-poop for you.",
    baseCost: 45,
    costScale: 1.65,
    maxLevel: 3,
  },
  {
    id: "hire_grinder",
    category: "crew",
    name: "Hire Spa & Grind Staff",
    description: "Washes and feeds the grinder from your stash.",
    baseCost: 70,
    costScale: 1.75,
    maxLevel: 2,
  },
  {
    id: "hire_vendor",
    category: "crew",
    name: "Hire Pack & Sell",
    description: "Boxes glitter and sells crates for you.",
    baseCost: 85,
    costScale: 1.8,
    maxLevel: 2,
  },
  {
    id: "hire_bot",
    category: "crew",
    name: "Poop-O-Matic 3000",
    description: "Auto-scoops nearby piles. Levels = range + speed.",
    baseCost: 110,
    costScale: 1.9,
    maxLevel: 3,
  },
  {
    id: "max_health",
    category: "player",
    name: "Sparkle Vest",
    description: "+25 max HP.",
    baseCost: 30,
    costScale: 1.4,
    maxLevel: 5,
  },
  {
    id: "move_speed",
    category: "player",
    name: "Rainbow Sneakers",
    description: "Move 10% faster — great for ranch runs.",
    baseCost: 35,
    costScale: 1.45,
    maxLevel: 4,
  },
];

export function upgradeCost(def: UpgradeDef, level: number) {
  return Math.floor(def.baseCost * Math.pow(def.costScale, level));
}

export function enemyStats(kind: EnemyKind, levelId: number) {
  const scale = 1 + (levelId - 1) * 0.08;
  switch (kind) {
    case "pest":
      return { hp: 20 * scale, speed: 2.8, damage: 3, radius: 0.6, color: 0xfff0f8, coin: 4, height: 1.0 };
    case "beetle":
      return { hp: 36 * scale, speed: 2.4, damage: 5, radius: 0.75, color: 0xe8d4ff, coin: 8, height: 1.15 };
    case "thief":
      return { hp: 28 * scale, speed: 3.6, damage: 2, radius: 0.6, color: 0xffd4a8, coin: 12, height: 1.2 };
    case "brute":
      return { hp: 90 * scale, speed: 1.9, damage: 8, radius: 1.1, color: 0xffb0d0, coin: 28, height: 1.9 };
  }
}

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    name: "Starter Paddock",
    subtitle: "Scoop → Spa → Grind → Box → Sell",
    width: 40,
    depth: 36,
    seed: 101,
    cropCount: 14,
    quota: 5,
    timeLimit: 320,
    spawn: { x: 0, z: 12 },
    spa: { x: -8, z: 4 },
    processor: { x: -8, z: -4 },
    packer: { x: 8, z: -4 },
    market: { x: 8, z: 4 },
    goalHint: "① Scoop → ② blue Spa → ③ purple Grind → ④ gold Box → ⑤ pink Sell",
    enemyWaves: [{ delay: 100, kind: "pest", count: 1 }],
    platforms: [{ x: 0, y: 1.0, z: -12, w: 4, d: 3 }],
  },
  {
    id: 2,
    name: "Busy Meadow",
    subtitle: "Hire help once the loop clicks.",
    width: 44,
    depth: 38,
    seed: 202,
    cropCount: 16,
    quota: 8,
    timeLimit: 300,
    spawn: { x: 0, z: 14 },
    spa: { x: -10, z: 5 },
    processor: { x: -10, z: -5 },
    packer: { x: 10, z: -5 },
    market: { x: 10, z: 5 },
    goalHint: "Keep the pipeline full. Hire a farmer ~45c.",
    enemyWaves: [
      { delay: 60, kind: "pest", count: 2 },
      { delay: 130, kind: "pest", count: 2 },
    ],
    platforms: [
      { x: -14, y: 1.2, z: 8, w: 4, d: 3 },
      { x: 14, y: 1.2, z: 8, w: 4, d: 3 },
    ],
  },
  {
    id: 3,
    name: "Glitter Canal",
    subtitle: "Longer runs, sillier stations.",
    width: 50,
    depth: 42,
    seed: 303,
    cropCount: 18,
    quota: 12,
    timeLimit: 300,
    spawn: { x: 0, z: 16 },
    spa: { x: -14, z: 6 },
    processor: { x: -14, z: -6 },
    packer: { x: 14, z: -6 },
    market: { x: 14, z: 6 },
    goalHint: "Vendors pack & sell. Pests may wander.",
    enemyWaves: [
      { delay: 50, kind: "pest", count: 2 },
      { delay: 95, kind: "beetle", count: 1 },
      { delay: 150, kind: "pest", count: 3 },
    ],
    platforms: [
      { x: 0, y: 1.6, z: 0, w: 5, d: 4 },
      { x: -16, y: 1.2, z: 10, w: 4, d: 3 },
      { x: 16, y: 1.2, z: 10, w: 4, d: 3 },
    ],
  },
  {
    id: 4,
    name: "Moonlit Meadow",
    subtitle: "Scale the glitter pipeline.",
    width: 54,
    depth: 46,
    seed: 404,
    cropCount: 20,
    quota: 16,
    timeLimit: 310,
    spawn: { x: 0, z: 18 },
    spa: { x: -16, z: 6 },
    processor: { x: -16, z: -6 },
    packer: { x: 16, z: -6 },
    market: { x: 16, z: 6 },
    goalHint: "Full crew recommended.",
    enemyWaves: [
      { delay: 45, kind: "pest", count: 3 },
      { delay: 90, kind: "beetle", count: 2 },
      { delay: 140, kind: "thief", count: 1 },
    ],
    platforms: [
      { x: -12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 0, y: 2.4, z: -10, w: 6, d: 4 },
    ],
  },
  {
    id: 5,
    name: "Sky Barn",
    subtitle: "High pads, high throughput.",
    width: 56,
    depth: 48,
    seed: 505,
    cropCount: 22,
    quota: 20,
    timeLimit: 320,
    spawn: { x: 0, z: 18 },
    spa: { x: -15, z: 5 },
    processor: { x: -15, z: -7 },
    packer: { x: 15, z: -7 },
    market: { x: 15, z: 5 },
    goalHint: "Jump for fun — the chain pays the bills.",
    enemyWaves: [
      { delay: 40, kind: "pest", count: 3 },
      { delay: 80, kind: "beetle", count: 2 },
      { delay: 120, kind: "thief", count: 2 },
      { delay: 170, kind: "pest", count: 4 },
    ],
    platforms: [
      { x: -18, y: 2.0, z: 4, w: 5, d: 4 },
      { x: 18, y: 2.0, z: 4, w: 5, d: 4 },
      { x: 0, y: 3.0, z: -8, w: 6, d: 5 },
    ],
  },
  {
    id: 6,
    name: "Final Ranch",
    subtitle: "Peak glitter economy.",
    width: 60,
    depth: 50,
    seed: 606,
    cropCount: 26,
    quota: 26,
    timeLimit: 340,
    spawn: { x: 0, z: 20 },
    spa: { x: -18, z: 6 },
    processor: { x: -18, z: -8 },
    packer: { x: 18, z: -8 },
    market: { x: 18, z: 6 },
    goalHint: "Automate everything.",
    enemyWaves: [
      { delay: 35, kind: "pest", count: 4 },
      { delay: 70, kind: "beetle", count: 3 },
      { delay: 110, kind: "thief", count: 2 },
      { delay: 160, kind: "brute", count: 1 },
    ],
    platforms: [
      { x: -20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 0, y: 3.2, z: 0, w: 7, d: 5 },
    ],
  },
];
