import type { LevelDef } from "./types";

export const LEVELS_ACT12: LevelDef[] = [
  {
    id: 1,
    name: "Starter Paddock",
    subtitle: "Easy warm-up",
    width: 40,
    depth: 36,
    seed: 101,
    cropCount: 18,
    quota: 12,
    timeLimit: 300,
    spawn: { x: 0, z: 12 },
    spa: { x: -8, z: 4 },
    processor: { x: -8, z: -4 },
    packer: { x: 8, z: -4 },
    market: { x: 8, z: 4 },
    goalHint: "Scoop pink piles · wash · glitter · box · sell",
    enemyWaves: [{ delay: 120, kind: "pest", count: 1 }],
    platforms: [{ x: 0, y: 1.0, z: -12, w: 4, d: 3 }],
  },
  {
    id: 2,
    name: "Busy Meadow",
    subtitle: "Unicorns + dinos",
    width: 44,
    depth: 38,
    seed: 202,
    cropCount: 20,
    quota: 16,
    timeLimit: 310,
    spawn: { x: 0, z: 14 },
    spa: { x: -10, z: 5 },
    processor: { x: -10, z: -5 },
    packer: { x: 10, z: -5 },
    market: { x: 10, z: 5 },
    goalHint: "Hire from floating buttons near stations",
    enemyWaves: [
      { delay: 70, kind: "pest", count: 1 },
      { delay: 100, kind: "raptor", count: 1 },
    ],
    platforms: [
      { x: -14, y: 1.2, z: 8, w: 4, d: 3 },
      { x: 14, y: 1.2, z: 8, w: 4, d: 3 },
    ],
  },
  {
    id: 3,
    name: "Glitter Canal",
    subtitle: "Dino visitors",
    width: 50,
    depth: 42,
    seed: 303,
    cropCount: 22,
    quota: 22,
    timeLimit: 320,
    spawn: { x: 0, z: 16 },
    spa: { x: -14, z: 6 },
    processor: { x: -14, z: -6 },
    packer: { x: 14, z: -6 },
    market: { x: 14, z: 6 },
    goalHint: "Hire a farmer when you can",
    enemyWaves: [
      { delay: 55, kind: "pest", count: 2 },
      { delay: 90, kind: "dino", count: 1 },
      { delay: 140, kind: "raptor", count: 1 },
    ],
    platforms: [
      { x: 0, y: 1.6, z: 0, w: 5, d: 4 },
      { x: -16, y: 1.2, z: 10, w: 4, d: 3 },
      { x: 16, y: 1.2, z: 10, w: 4, d: 3 },
    ],
  },
  {
    id: 4,
    name: "Moonlit Meadow",
    subtitle: "Mixed herd",
    width: 54,
    depth: 46,
    seed: 404,
    cropCount: 24,
    quota: 28,
    timeLimit: 330,
    spawn: { x: 0, z: 18 },
    spa: { x: -16, z: 6 },
    processor: { x: -16, z: -6 },
    packer: { x: 16, z: -6 },
    market: { x: 16, z: 6 },
    goalHint: "Automate the chain",
    enemyWaves: [
      { delay: 50, kind: "pest", count: 2 },
      { delay: 80, kind: "dino", count: 1 },
      { delay: 110, kind: "beetle", count: 1 },
      { delay: 150, kind: "raptor", count: 2 },
    ],
    platforms: [
      { x: -12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 12, y: 1.8, z: 8, w: 5, d: 3 },
      { x: 0, y: 2.4, z: -10, w: 6, d: 4 },
    ],
  },
  {
    id: 5,
    name: "Sky Barn",
    subtitle: "Heights + hires",
    width: 56,
    depth: 48,
    seed: 505,
    cropCount: 26,
    quota: 34,
    timeLimit: 340,
    spawn: { x: 0, z: 18 },
    spa: { x: -16, z: 7 },
    processor: { x: -16, z: -7 },
    packer: { x: 16, z: -7 },
    market: { x: 16, z: 7 },
    goalHint: "Keep selling — quota is a real target now",
    enemyWaves: [
      { delay: 45, kind: "pest", count: 2 },
      { delay: 75, kind: "dino", count: 2 },
      { delay: 110, kind: "raptor", count: 2 },
      { delay: 160, kind: "thief", count: 1 },
    ],
    platforms: [
      { x: -18, y: 2.0, z: 6, w: 5, d: 4 },
      { x: 18, y: 2.0, z: 6, w: 5, d: 4 },
      { x: 0, y: 2.8, z: -8, w: 6, d: 4 },
    ],
  },
  {
    id: 6,
    name: "Final Ranch",
    subtitle: "Act 2 finale",
    width: 60,
    depth: 50,
    seed: 606,
    cropCount: 28,
    quota: 40,
    timeLimit: 350,
    spawn: { x: 0, z: 20 },
    spa: { x: -18, z: 6 },
    processor: { x: -18, z: -7 },
    packer: { x: 18, z: -7 },
    market: { x: 18, z: 6 },
    goalHint: "Crew + robots earn their keep",
    enemyWaves: [
      { delay: 40, kind: "pest", count: 3 },
      { delay: 70, kind: "dino", count: 2 },
      { delay: 100, kind: "raptor", count: 2 },
      { delay: 140, kind: "beetle", count: 2 },
      { delay: 180, kind: "thief", count: 1 },
    ],
    platforms: [
      { x: -20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 20, y: 2.2, z: 8, w: 5, d: 4 },
      { x: 0, y: 3.2, z: 0, w: 7, d: 5 },
    ],
  },
  {
    id: 7,
    name: "Poop Carnival",
    subtitle: "Ferris-wheel vibes",
    width: 62,
    depth: 52,
    seed: 707,
    cropCount: 30,
    quota: 46,
    timeLimit: 360,
    spawn: { x: 0, z: 20 },
    spa: { x: -18, z: 7 },
    processor: { x: -18, z: -8 },
    packer: { x: 18, z: -8 },
    market: { x: 18, z: 7 },
    goalHint: "Crowds want crates — keep the queue happy",
    enemyWaves: [
      { delay: 35, kind: "pest", count: 3 },
      { delay: 65, kind: "raptor", count: 2 },
      { delay: 100, kind: "dino", count: 2 },
      { delay: 140, kind: "beetle", count: 2 },
    ],
    platforms: [
      { x: -22, y: 2.4, z: 6, w: 5, d: 4 },
      { x: 22, y: 2.4, z: 6, w: 5, d: 4 },
      { x: 0, y: 3.4, z: -12, w: 8, d: 5 },
    ],
  },
  {
    id: 8,
    name: "Rainbow Gorge",
    subtitle: "Narrow paths",
    width: 48,
    depth: 56,
    seed: 808,
    cropCount: 32,
    quota: 52,
    timeLimit: 360,
    spawn: { x: 0, z: 22 },
    spa: { x: -12, z: 8 },
    processor: { x: -12, z: -8 },
    packer: { x: 12, z: -8 },
    market: { x: 12, z: 8 },
    goalHint: "Tight map — plan your path",
    enemyWaves: [
      { delay: 30, kind: "thief", count: 2 },
      { delay: 60, kind: "raptor", count: 3 },
      { delay: 100, kind: "dino", count: 2 },
      { delay: 150, kind: "brute", count: 1 },
    ],
    platforms: [
      { x: 0, y: 2.0, z: 4, w: 4, d: 12 },
      { x: -10, y: 2.8, z: -4, w: 4, d: 4 },
      { x: 10, y: 2.8, z: -4, w: 4, d: 4 },
    ],
  },
  {
    id: 9,
    name: "Dino Disco Field",
    subtitle: "Party pests",
    width: 64,
    depth: 54,
    seed: 909,
    cropCount: 34,
    quota: 58,
    timeLimit: 370,
    spawn: { x: 0, z: 22 },
    spa: { x: -20, z: 6 },
    processor: { x: -20, z: -8 },
    packer: { x: 20, z: -8 },
    market: { x: 20, z: 6 },
    goalHint: "Jukebox tips help — dinos dance in",
    enemyWaves: [
      { delay: 25, kind: "dino", count: 3 },
      { delay: 55, kind: "raptor", count: 2 },
      { delay: 90, kind: "pest", count: 3 },
      { delay: 130, kind: "dino", count: 2 },
      { delay: 170, kind: "brute", count: 1 },
    ],
    platforms: [
      { x: -24, y: 2.2, z: 10, w: 5, d: 4 },
      { x: 24, y: 2.2, z: 10, w: 5, d: 4 },
      { x: 0, y: 3.6, z: -6, w: 8, d: 6 },
    ],
  },
];
