import type { LevelDef } from "./types";

export const LEVELS_ACT345: LevelDef[] = [
  {
    id: 10,
    name: "Bubble Spa District",
    subtitle: "Wash bottleneck",
    width: 66,
    depth: 56,
    seed: 1010,
    cropCount: 34,
    quota: 34,
    timeLimit: 390,
    spawn: { x: 0, z: 24 },
    spa: { x: -20, z: 8 },
    processor: { x: -20, z: -10 },
    packer: { x: 20, z: -10 },
    market: { x: 20, z: 8 },
    goalHint: "Upgrade Spa+ and hire spa crew",
    enemyWaves: [
      { delay: 30, kind: "pest", count: 3 },
      { delay: 55, kind: "beetle", count: 2 },
      { delay: 90, kind: "raptor", count: 3 },
      { delay: 140, kind: "thief", count: 2 },
    ],
    platforms: [
      { x: -22, y: 2.4, z: 0, w: 6, d: 5 },
      { x: 22, y: 2.4, z: 0, w: 6, d: 5 },
      { x: 0, y: 3.2, z: -14, w: 8, d: 5 },
    ],
  },
  {
    id: 11,
    name: "Glitter Factory Row",
    subtitle: "Grind hard",
    width: 68,
    depth: 58,
    seed: 1111,
    cropCount: 36,
    quota: 38,
    timeLimit: 400,
    spawn: { x: 0, z: 24 },
    spa: { x: -22, z: 8 },
    processor: { x: -22, z: -10 },
    packer: { x: 22, z: -10 },
    market: { x: 22, z: 8 },
    goalHint: "Auto hopper is your friend",
    enemyWaves: [
      { delay: 25, kind: "pest", count: 4 },
      { delay: 50, kind: "dino", count: 2 },
      { delay: 80, kind: "raptor", count: 3 },
      { delay: 120, kind: "beetle", count: 2 },
      { delay: 170, kind: "brute", count: 1 },
    ],
    platforms: [
      { x: -24, y: 2.6, z: 8, w: 6, d: 4 },
      { x: 24, y: 2.6, z: 8, w: 6, d: 4 },
      { x: 0, y: 3.8, z: -8, w: 9, d: 6 },
    ],
  },
  {
    id: 12,
    name: "Bow & Box Boulevard",
    subtitle: "Packing rush",
    width: 70,
    depth: 58,
    seed: 1212,
    cropCount: 38,
    quota: 42,
    timeLimit: 400,
    spawn: { x: 0, z: 26 },
    spa: { x: -22, z: 8 },
    processor: { x: -22, z: -12 },
    packer: { x: 22, z: -12 },
    market: { x: 22, z: 8 },
    goalHint: "Box+ and seller hires",
    enemyWaves: [
      { delay: 20, kind: "pest", count: 3 },
      { delay: 45, kind: "thief", count: 2 },
      { delay: 75, kind: "raptor", count: 3 },
      { delay: 110, kind: "dino", count: 3 },
      { delay: 160, kind: "brute", count: 1 },
    ],
    platforms: [
      { x: -26, y: 2.8, z: 6, w: 6, d: 5 },
      { x: 26, y: 2.8, z: 6, w: 5, d: 5 },
      { x: 0, y: 4.0, z: -6, w: 10, d: 6 },
    ],
  },
  {
    id: 13,
    name: "VIP Market Night",
    subtitle: "High rollers",
    width: 72,
    depth: 60,
    seed: 1313,
    cropCount: 40,
    quota: 46,
    timeLimit: 410,
    spawn: { x: 0, z: 26 },
    spa: { x: -24, z: 8 },
    processor: { x: -24, z: -12 },
    packer: { x: 24, z: -12 },
    market: { x: 24, z: 8 },
    goalHint: "Price+ pays off big tonight",
    enemyWaves: [
      { delay: 20, kind: "thief", count: 3 },
      { delay: 50, kind: "raptor", count: 3 },
      { delay: 85, kind: "dino", count: 2 },
      { delay: 120, kind: "beetle", count: 2 },
      { delay: 170, kind: "brute", count: 2 },
    ],
    platforms: [
      { x: -28, y: 3.0, z: 8, w: 6, d: 5 },
      { x: 28, y: 3.0, z: 8, w: 6, d: 5 },
      { x: 0, y: 4.2, z: -10, w: 10, d: 6 },
    ],
  },
  {
    id: 14,
    name: "Unicorn Stampede",
    subtitle: "Herd pressure",
    width: 74,
    depth: 62,
    seed: 1414,
    cropCount: 42,
    quota: 50,
    timeLimit: 420,
    spawn: { x: 0, z: 28 },
    spa: { x: -24, z: 10 },
    processor: { x: -24, z: -12 },
    packer: { x: 24, z: -12 },
    market: { x: 24, z: 10 },
    goalHint: "Gun upgrades matter — don't get swarmed",
    enemyWaves: [
      { delay: 15, kind: "pest", count: 5 },
      { delay: 40, kind: "pest", count: 4 },
      { delay: 70, kind: "raptor", count: 3 },
      { delay: 100, kind: "dino", count: 3 },
      { delay: 140, kind: "brute", count: 1 },
      { delay: 180, kind: "thief", count: 2 },
    ],
    platforms: [
      { x: -28, y: 3.0, z: 12, w: 6, d: 5 },
      { x: 28, y: 3.0, z: 12, w: 6, d: 5 },
      { x: 0, y: 4.4, z: -8, w: 12, d: 6 },
    ],
  },
  {
    id: 15,
    name: "Crystal Compost Hills",
    subtitle: "Overflow salvage",
    width: 76,
    depth: 64,
    seed: 1515,
    cropCount: 44,
    quota: 54,
    timeLimit: 430,
    spawn: { x: 0, z: 28 },
    spa: { x: -26, z: 10 },
    processor: { x: -26, z: -14 },
    packer: { x: 26, z: -14 },
    market: { x: 26, z: 10 },
    goalHint: "Compost excess · fountain heal often",
    enemyWaves: [
      { delay: 20, kind: "beetle", count: 3 },
      { delay: 50, kind: "dino", count: 3 },
      { delay: 85, kind: "raptor", count: 3 },
      { delay: 130, kind: "thief", count: 2 },
      { delay: 180, kind: "brute", count: 2 },
    ],
    platforms: [
      { x: -30, y: 3.2, z: 6, w: 6, d: 5 },
      { x: 30, y: 3.2, z: 6, w: 6, d: 5 },
      { x: -12, y: 4.0, z: -12, w: 6, d: 5 },
      { x: 12, y: 4.0, z: -12, w: 6, d: 5 },
    ],
  },
  {
    id: 16,
    name: "Jukebox Junction",
    subtitle: "Tips & tunes",
    width: 78,
    depth: 64,
    seed: 1616,
    cropCount: 46,
    quota: 58,
    timeLimit: 430,
    spawn: { x: 0, z: 30 },
    spa: { x: -26, z: 10 },
    processor: { x: -26, z: -14 },
    packer: { x: 26, z: -14 },
    market: { x: 26, z: 10 },
    goalHint: "Dance for tips between sells",
    enemyWaves: [
      { delay: 18, kind: "pest", count: 4 },
      { delay: 45, kind: "raptor", count: 4 },
      { delay: 80, kind: "dino", count: 3 },
      { delay: 120, kind: "beetle", count: 3 },
      { delay: 170, kind: "brute", count: 2 },
    ],
    platforms: [
      { x: -30, y: 3.4, z: 10, w: 7, d: 5 },
      { x: 30, y: 3.4, z: 10, w: 7, d: 5 },
      { x: 0, y: 4.6, z: -10, w: 12, d: 7 },
    ],
  },
  {
    id: 17,
    name: "Boss Ranch Showdown",
    subtitle: "Mega brute wave",
    width: 80,
    depth: 66,
    seed: 1717,
    cropCount: 48,
    quota: 64,
    timeLimit: 450,
    spawn: { x: 0, z: 30 },
    spa: { x: -28, z: 10 },
    processor: { x: -28, z: -14 },
    packer: { x: 28, z: -14 },
    market: { x: 28, z: 10 },
    goalHint: "Survive the brutes · sell through the chaos",
    enemyWaves: [
      { delay: 15, kind: "pest", count: 4 },
      { delay: 40, kind: "dino", count: 3 },
      { delay: 70, kind: "raptor", count: 4 },
      { delay: 110, kind: "brute", count: 2 },
      { delay: 150, kind: "thief", count: 3 },
      { delay: 200, kind: "brute", count: 2 },
    ],
    platforms: [
      { x: -32, y: 3.6, z: 8, w: 7, d: 5 },
      { x: 32, y: 3.6, z: 8, w: 7, d: 5 },
      { x: 0, y: 5.0, z: -8, w: 14, d: 8 },
    ],
  },
  {
    id: 18,
    name: "Infinite Parade",
    subtitle: "Endgame ranch",
    width: 84,
    depth: 70,
    seed: 1818,
    cropCount: 52,
    quota: 72,
    timeLimit: 480,
    spawn: { x: 0, z: 32 },
    spa: { x: -30, z: 12 },
    processor: { x: -30, z: -16 },
    packer: { x: 30, z: -16 },
    market: { x: 30, z: 12 },
    goalHint: "Master the full pipeline · celebrate",
    enemyWaves: [
      { delay: 12, kind: "pest", count: 5 },
      { delay: 35, kind: "raptor", count: 4 },
      { delay: 60, kind: "dino", count: 4 },
      { delay: 95, kind: "beetle", count: 3 },
      { delay: 130, kind: "thief", count: 3 },
      { delay: 170, kind: "brute", count: 3 },
      { delay: 220, kind: "raptor", count: 3 },
    ],
    platforms: [
      { x: -34, y: 3.8, z: 12, w: 7, d: 6 },
      { x: 34, y: 3.8, z: 12, w: 7, d: 6 },
      { x: -16, y: 4.5, z: -12, w: 8, d: 6 },
      { x: 16, y: 4.5, z: -12, w: 8, d: 6 },
      { x: 0, y: 5.5, z: 0, w: 12, d: 8 },
    ],
  },
];
